CREATE TABLE EXAM(
EXAM_CODE VARCHAR(10) PRIMARY KEY,
EXAM_TITLE VARCHAR(50)
);

CREATE TABLE EXAM_SCHEDULE(
SCHEDULE_ID NUMERIC PRIMARY KEY,
EXAM_CODE VARCHAR(10) NOT NULL,
SCHEDULE_DATE DATE NOT NULL,
START_TIME DATETIME NOT NULL,
END_TIME DATETIME NOT NULL
);

CREATE TABLE STUDENT(
STUDENT_ID VARCHAR(10) NOT NULL,
STUDENT_NAME VARCHAR(20) NOT NULL,
USER_NAME VARCHAR(10) NOT NULL,
PASSWORD VARCHAR(10) NOT NULL,
SCHEDULE_ID NUMERIC
);

alter table EXAM_SCHEDULE
add constraint EXAM_SCHEDULE_EXAM_CODE_FK FOREIGN KEY ( EXAM_CODE ) references EXAM(EXAM_CODE);

alter table STUDENT
add constraint STUDENT_SCHEDULE_ID_FK FOREIGN KEY ( SCHEDULE_ID ) references EXAM_SCHEDULE(SCHEDULE_ID);

